### ISSUE TITLE
Create Tag and Listing Tags produce no output

### ISSUE THREAD

**Issue by kiwironnie** [leftstick/vscode-git-tags#1]
Using Visual Studio Cod 1.12.2 under Ubuntu 16.04, git installed and working.
Selecting Create Tag or Listing Tags from the git menu doesn't do anything, no dialogue.
Tried restarting .. same.
Please advise.
Many thanks
Ron

**Comment by leftstick** [comment]
What is your `git` version?

**Comment by kiwironnie** [comment]
It's 2.7.4 thanks Howard.

**Comment by kiwironnie** [comment]
Further - Upgrading to git version 2.13.0 the problem still exists, no dialogue when 'Create Tag' or 'Listing Tags' is clicked from the source control menu. The other source control menu items are working ok.

**Comment by leftstick** [comment]
You mean even click "Create Tag", no `inputbox` shown as below:

![screen shot 2017-06-05 at 10 29 26 am](https://cloud.githubusercontent.com/assets/1059956/26768362/e185e146-49d9-11e7-8f63-c5f2682a9adb.png)

**Comment by kiwironnie** [comment]
Yes, that's right, no input box or anything.  I've tried uninstalling and re-installing, same.
In the Command Pallet selecting Create Tag or Listing Tags gives:
command 'extension.gitcreatetag' not found
command 'extension.gittags' not found
vscode-git-tags is clearly shown in the list of extensions as 'installed', with commands in the source control menu.

**Comment by leftstick** [comment]
ohh.. weird.   I don't have a ubuntu env, but i fixed a potential issue, can you give a try with `1.0.1`?

**Comment by kiwironnie** [comment]
Thanks. But darn!  Tried upgrading, then uninstalling, re-installing, restarting, but it's the same.  Pity as it would be very useful, as beginning to use git tags in anger!

**Comment by leftstick** [comment]
I will try to find a ubuntu laptop, sorry for the inconvenience

**Comment by kiwironnie** [comment]
Thanks. It would be very cool indeed if you manage to get it running on Ubuntu.

**Comment by leftstick** [comment]
I tried debug on an ubuntu laptop, it's working while debugging. But once i installed it via extension manager, error happened just like you said. I am not really sure what happened while `vscode` loading this extension, so i report it [28021](https://github.com/Microsoft/vscode/issues/28021), let's see what we get from `vscode` team

**Comment by kiwironnie** [comment]
Hey, that was quick! Glad it wasn't just me then (not unknown)! Hopefully you'll soon get something useful back from the vscode team.  Many thanks.

**Comment by leftstick** [comment]
Seems both your ubuntu `16.04` and my `12.04.3` are not supported. Sorry about that

**Comment by kiwironnie** [comment]
Hmm, right. Guess MS would rather put the effort into Windows and happy to trail behind the rest.
Anyway thanks for trying.

**Comment by Tyriar** [comment]
I reopened the issue and assigned the extension API owner, it wasn't mentioned that it occurred in Ubuntu 16. [We have a statement of support](https://code.visualstudio.com/docs/supporting/requirements) to avoid wasting time dealing with older OS issues.

> Guess MS would rather put the effort into Windows and happy to trail behind the rest.

I use Ubuntu every day - Linux support is very much a priority.

**Comment by kiwironnie** [comment]
Ok thanks Tyriar, sounds promising.
Couldn't see a 'statement of support' at the link that you provided, other than 'has been tested with 14.04'. In any case are you saying that 16.04 is supported?  If so I withdraw my earlier remark.

**Comment by Tyriar** [comment]
Yeah the wording could be better, basically we try to support those versions and above.

**Comment by leftstick** [comment]
OK, then let's keep this issue open. Thanks for you guys effort @kiwironnie , @Tyriar

**Comment by leftstick** [comment]
@kiwironnie  please give a try with `1.0.2`, i don't know what happened to my `publish-process`, something changed the output files' name into lowercase. So i re-publish this extension again, it's working now on my ubuntu 12. so should working on yours

**Comment by kiwironnie** [comment]
That was quick. Excellent thanks leftstick. Both dialogues now show. It should prove very useful. Best wishes, Ron.

**Comment by Tyriar** [comment]
Good to hear 😃
