### ISSUE TITLE
亂碼

### ISSUE THREAD

**Issue by swdcgghxa** [leftstick/vscode-git-tags#10]
沒辦法用英文以外的語言設定標籤

**Comment by leftstick** [comment]
![coding](https://user-images.githubusercontent.com/1059956/49133420-064a4f80-f31b-11e8-9d54-2b72c4988611.gif)

我试了下没什么问题，麻烦提供下详细的信息，譬如：vscode版本，`vscode-git-tags`版本，操作系统版本。。。

**Comment by swdcgghxa** [comment]
![git-tag](https://user-images.githubusercontent.com/38091497/90200071-1b298800-de09-11ea-8e3d-d3c58640cee4.png)
不過現在正常了。
