### ISSUE TITLE
Error message during creating of tag

### ISSUE THREAD

**Issue by nieselfriem** [leftstick/vscode-git-tags#11]
Hello,

as soon as I want to create a tag, I get the error message below. GIT itself is configured correctly. 
The command "E:\Program" is either written incorrectly or
could not be found.
The path to my git: "E:\\Program Files\\Git\\cmd\\git.exe"

Gteetings 
nieselfriem

**Comment by leftstick** [comment]
It's probably caused you are missing it from `PATH` env, try config msysgit's binary to your `PATH`, you can check [https://stackoverflow.com/questions/11000869/command-line-git-on-windows](https://stackoverflow.com/questions/11000869/command-line-git-on-windows)
