### ISSUE TITLE
'vscode.previewHtml' is deprecated

### ISSUE THREAD

**Issue by SaschaMuench** [leftstick/vscode-git-tags#12]
Message from VS Code during "Listing Tags":

Extension 'howardzuo.vscode-git-tags' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by leftstick** [comment]
Would you mind give me a PR? I am afraid i don't have time for this upgrade

**Comment by leftstick** [comment]
fixed in `1.4.0`
