### ISSUE TITLE
Change some colors in the Listing Tags page

### ISSUE THREAD

**Issue by doggy8088** [leftstick/vscode-git-tags#3]
There are links in the Listing Tags page that you using `lightgreen` as the hover link color which is really burning my eyes.  Hope to change to a comfort color.  Thanks! 👍

**Comment by leftstick** [comment]
Sure, do you have any suggestion?

Anyway, i have a plan to refactor  this whole feature in some other way. Mission should start in  coming week.

**Comment by doggy8088** [comment]
Looking forward ... 👍
