### ISSUE TITLE
Styling of tag name overrides message

### ISSUE THREAD

**Issue by danyill** [leftstick/vscode-git-tags#4]
See screenshot below, as of installation installed today:

![image](https://user-images.githubusercontent.com/674783/31417040-a269f28a-ae89-11e7-872f-b69f6db59e50.png)

The tag name is rather long, `release_14Aug2017.001.000.`

Could this automatically wrap or columns extend via css.

Thanks for this extension.

**Comment by leftstick** [comment]
Sure, let me adjust later

**Comment by danyill** [comment]
Thank you

**Comment by leftstick** [comment]
@danyill  please try `1.1.2`

**Comment by danyill** [comment]
That's much better, thank you.

Could we increase the space a little more (as on a typical screen there is a lot of space avaiable) and add a tooltip in case the tag is still not completely displayed? Often it's the last few digits which are important in a version number.

![image](https://user-images.githubusercontent.com/674783/31460107-c40c0db8-af21-11e7-9a9e-1b6d3f914ca6.png)
